# -*- coding: utf-8 -*-
"""Ejercicio FFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOhzhDnHOzKei0MqY9dI9JArQWI4Utgh
"""

!pip install librosa
!pip install soundfile

import librosa
import numpy as np
# Load the mp3 file
# sr=None preserves the original sampling rate; otherwise, it defaults to 22050 Hz
signal, sr = librosa.load('/content/drive/MyDrive/Nota_CM_piano.mp3', sr=None)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 4))
plt.plot(signal)
plt.title("MP3 Signal Waveform")
plt.xlabel("Sample Index")
plt.ylabel("Amplitude")
plt.show()

import numpy as np
from scipy.fft import fft, fftfreq

fs = 100

N = len(signal)
yf = fft(signal)
xf = fftfreq(N, 1 / fs)

plt.plot(xf[:N//2], 2.0/N * np.abs(yf[:N//2]))
plt.title('espectro')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Amplitud')
plt.xlim(0, 30)
plt.grid()

# REGULAR. NO ESTA MARCADO EL LAV_7. ENTREGAR EL .IPYNBOOK CON EL CODIGO COMPLETO Y LOS GRAFICOS. 
# PERO NO ESTA COMPLETO, SE CALIFICARA CON BASE EN LO ENTREGADO.
# NO DESARROLLA EL PUNTO B) NO VEO LOS PICOS DE LAS FRECUENCIAS FUNDAMENTALES. NOTA 3.5